/*
 * SYRIATECH — the product page.
 * Generated by tools/split-i18n.cjs from i18n.js. Do not edit here; edit the
 * dictionary and re-run the tool.
 *
 * This is part of the same dictionary, in a separate file so that a page pays
 * only for the words it shows. It merges into window.I18N.dict, so nothing
 * that reads a string needs to know which file it came from.
 */
(function () {
  if (!window.I18N || !window.I18N.dict) return;
  const add = {
    ar: {
      "pdpBreadcrumb": "مسار التصفح",
      "pdpNotFound": "هذا المنتج لم يعد موجوداً",
      "relatedTitle": "منتجات مشابهة",
      "relatedInStockTitle": "بدائل متوفرة الآن",
      "pdpBuyNow": "اشترِ الآن",
      "pdpCartHint": "اجمع أكثر من منتج وأرسلها في طلب واحد",
      "pdpDiscount": "خصم {p}",
      "pdpLinkCopied": "تم نسخ رابط المنتج",
      "pdpStickyBar": "شراء سريع",
      "pdpPolicyOpen": "اعرف التفاصيل",
      "pdpDistributor": "سيريا تك موزّع معتمد في سوريا لعلامات {brands}، والضمان ضمان المصنّع.",
      "pdpListSep": "، ",
      "pdpListAnd": "، ",
      "pdpMoreBrandsOne": "علامة أخرى",
      "pdpMoreBrandsTwo": "علامتين أخريين",
      "pdpMoreBrandsFew": "{n} علامات أخرى",
      "pdpMoreBrandsMany": "{n} علامة أخرى",
      "galleryTitle": "صور المنتج",
      "galleryCounter": "{n} / {total}",
      "galleryPrev": "الصورة السابقة",
      "galleryNext": "الصورة التالية",
      "galleryInUse": "لوحة شرح من الشركة المصنّعة",
      "galleryNoPhoto": "لا توجد صورة لهذا المنتج",
      "variantPick": "اختر اللون",
      "variantColour": "اللون: {name}",
      "variantOut": "غير متوفر بهذا اللون",
      "variantChanged": "تم اختيار {name} — {price}",
      "specInTheBox": "ما في العلبة",
      "specBoxContentsTitles": "[\"محتويات العلبة\",\"محتويات الطقم\",\"محتويات العبوة\"]",
      "specNoteTitles": "[\"ملاحظة*\",\"تنويه*\",\"إخلاء مسؤولية*\"]",
    },
    en: {
      "pdpBreadcrumb": "Breadcrumb",
      "pdpNotFound": "This product is no longer here",
      "relatedTitle": "You may also like",
      "relatedInStockTitle": "Alternatives in stock now",
      "pdpBuyNow": "Buy now",
      "pdpCartHint": "Collect several items and send them as one order",
      "pdpDiscount": "{p} off",
      "pdpLinkCopied": "Product link copied",
      "pdpStickyBar": "Quick buy",
      "pdpPolicyOpen": "See the details",
      "pdpDistributor": "Syriatech is an authorised distributor in Syria for {brands}, and the warranty is the manufacturer's own.",
      "pdpListSep": ", ",
      "pdpListAnd": " and ",
      "pdpMoreBrandsOne": "one more brand",
      "pdpMoreBrandsTwo": "two more brands",
      "pdpMoreBrandsFew": "{n} more brands",
      "pdpMoreBrandsMany": "{n} more brands",
      "galleryTitle": "Product photos",
      "galleryCounter": "{n} / {total}",
      "galleryPrev": "The previous photo",
      "galleryNext": "The next photo",
      "galleryInUse": "An information panel from the maker",
      "galleryNoPhoto": "There is no photo for this product",
      "variantPick": "Choose a colour",
      "variantColour": "Colour: {name}",
      "variantOut": "Not available in this colour",
      "variantChanged": "{name} selected — {price}",
      "specInTheBox": "In the box",
      "specBoxContentsTitles": "[\"What You Get\",\"What's in the Box\",\"In the Box\",\"Box Contents\"]",
      "specNoteTitles": "[\"Note*\",\"*Note\",\"*Notes\",\"Disclaimer*\"]",
    },
    tr: {
      "pdpBreadcrumb": "Sayfa yolu",
      "pdpNotFound": "Bu ürün artık burada değil",
      "relatedTitle": "Bunlar da ilginizi çekebilir",
      "relatedInStockTitle": "Şu an stokta olan alternatifler",
      "pdpBuyNow": "Hemen al",
      "pdpCartHint": "Birkaç ürünü toplayıp tek siparişte gönderin",
      "pdpDiscount": "{p} indirim",
      "pdpLinkCopied": "Ürün bağlantısı kopyalandı",
      "pdpStickyBar": "Hızlı satın alma",
      "pdpPolicyOpen": "Ayrıntıları görün",
      "pdpDistributor": "Syriatech, Suriye'de {brands} için yetkili distribütördür ve garanti üreticinin kendi garantisidir.",
      "pdpListSep": ", ",
      "pdpListAnd": " ve ",
      "pdpMoreBrandsOne": "bir marka daha",
      "pdpMoreBrandsTwo": "iki marka daha",
      "pdpMoreBrandsFew": "{n} marka daha",
      "pdpMoreBrandsMany": "{n} marka daha",
      "galleryTitle": "Ürün fotoğrafları",
      "galleryCounter": "{n} / {total}",
      "galleryPrev": "Önceki fotoğraf",
      "galleryNext": "Sonraki fotoğraf",
      "galleryInUse": "Üreticinin bilgi görseli",
      "galleryNoPhoto": "Bu ürün için fotoğraf yok",
      "variantPick": "Renk seçin",
      "variantColour": "Renk: {name}",
      "variantOut": "Bu renkte mevcut değil",
      "variantChanged": "{name} seçildi — {price}",
      "specInTheBox": "Kutuda",
      "specBoxContentsTitles": "[\"Kutu İçeriği\",\"Set İçeriği\",\"Paket İçeriği\"]",
      "specNoteTitles": "[\"Önemli Not\",\"*Notu\",\"Uyarı*\",\"Feragatname*\"]",
    }
  };
  for (const code of Object.keys(add)) {
    const target = window.I18N.dict[code] || (window.I18N.dict[code] = {});
    for (const key of Object.keys(add[code])) {
      /* A dotted key is stored flat; I18N.t walks both shapes. */
      if (target[key] === undefined) target[key] = add[code][key];
    }
  }
  if (typeof window.I18N.onChunk === "function") window.I18N.onChunk("i18n-pdp.js");
})();
